config firewall addrgrp
    edit "G_BAD-GROUP"
    next
end
config firewall policy
    edit 0
        set name "BLOCK BAD-GROUP"
        set srcintf "port1"
        set dstintf "wan1"
        set srcaddr "G_BAD-GROUP"
        set dstaddr "all"
        set schedule "always"
        set service "ALL"
		set action deny
        set logtraffic all
    next
    edit 0
        set name "LAN 2 WAN"
        set srcintf "port1"
        set dstintf "wan1"
        set action accept
        set srcaddr "all"
        set dstaddr "all"
        set schedule "always"
        set service "ALL"
        set logtraffic all
        set nat enable
    next
end
config system automation-action
    edit "CREATE-BAD-HOST"
        set action-type cli-script
        set script "config firewall address
edit \"H_%%log.epip%%\"
set subnet %%log.epip%% 255.255.255.255
set comment \"%%log.mkey%%_%%log.date%%\"
next
end
config firewall addrgrp
edit G_BAD-GROUP
append member \"H_%%log.epip%%\"
next
end"
        set accprofile "super_admin"
    next
end
config system automation-trigger
    edit "Incoming Webhook Call"
        set description "An incoming webhook call is received"
        set event-type incoming-webhook
    next
end
config system automation-stitch
    edit "FAZ-WEBHOOK"
        set trigger "Incoming Webhook Call"
        config actions
            edit 1
                set action "CREATE-BAD-HOST"
                set required enable
            next
        end
    next
end    